"""Basic Model redirections happen here. You define a model, and call a get_model function from this notebook. After that, the notebook redirectes the model to the correct model type."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02k_models.ipynb.

# %% auto #0
__all__ = ['create_model']

# %% ../../nbs/02k_models.ipynb #bb434c70
import random
import numpy as np
import os
import torch

import fedai.models.vision as vision_models


# %% ../../nbs/02k_models.ipynb #2f5ecfed
def create_model(cfg):

    torch.manual_seed(cfg.get("random_seed", 42))
    np.random.seed(cfg.get("random_seed", 42))
    random.seed(cfg.get("random_seed", 42))
    
    if cfg.model.name in vision_models.list_model_names() and cfg.data.modality == ['Vision']:
        return vision_models.create_model(**cfg.model)
    
    raise ValueError(f"Model '{cfg.model.name}' is not recognized, the available models are: {vision_models.list_model_names()}")

