"""MLPs, Logistic and Linear Regression, and any model that is not specific to a domain. For vision and text models, see `02b_models.vision` and `02c_models.text` respectively."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02a_models.generics.ipynb.

# %% auto #0
__all__ = ['LogisticRegression', 'MLP']

# %% ../../nbs/02a_models.generics.ipynb #e2289923
from fastcore.utils import *  
import torch
from torch import nn
from torch.nn import functional as F

# %% ../../nbs/02a_models.generics.ipynb #c622e58b
class LogisticRegression(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_dim, num_classes)

    def forward(self, x):
        x = x.view(-1, x.shape[1]*x.shape[-2]*x.shape[-1])
        return self.linear(x)

# %% ../../nbs/02a_models.generics.ipynb #619aefed
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes):
        super(MLP, self).__init__()
        self.layer_input = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout()
        self.layer_hidden = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x = x.view(-1, x.shape[1]*x.shape[-2]*x.shape[-1])
        x = self.layer_input(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.layer_hidden(x)
        return x
