"""The core abstraction for ditto client."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10h_clients.ditto.ipynb.

# %% auto #0
__all__ = ['ClientDitto', 'ptrain', 'train', 'fit']

# %% ../../nbs/10h_clients.ditto.ipynb #95d57626
from fastcore.utils import *
from fastcore.all import *
import copy
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

from .base_client import BaseClient
from ..utils.registery import AlgorithmRegistry

# %% ../../nbs/10h_clients.ditto.ipynb #c4456ff3
@AlgorithmRegistry.register_client("ditto")
class ClientDitto(BaseClient):
    def __init__(self,
                 id, # Unique identifier for the client
                 cfg, # A configuration object containing all the necessary parameters for training and evaluation.
                 train_loader, 
                 test_loader,
                 state, # A dictionary containing the model, optimizer and any changing component needed.
                 criterion,
                 device= None,
                 t= 0,
                 **kwargs # extra client-specific parameters (that cannot be passed in state and cfg), can be passed as here.
                 ):  
                 
        super().__init__(id, cfg, train_loader, test_loader, state, criterion, device, t, **kwargs)
        

# %% ../../nbs/10h_clients.ditto.ipynb #c309651c
def ptrain(self: ClientDitto):
    self.model = self.model.to(self.device)
    self.model_per = self.model_per.to(self.device)
    self.model.train()
    self.model_per.train()
    for _ in range(self.cfg.local_epochs):
        for i, batch in enumerate(self.train_loader):
            batch = self.send_to_device(batch)
            self.optimizer.zero_grad()
            X, y = batch[self.data_key], batch[self.label_key]
            outputs = self.model_per(X)
            loss = self.criterion(outputs, y)
            self.optimizer_per.zero_grad()
            loss.backward()
            self.optimizer_per.step(self.model.parameters(), self.device)


# %% ../../nbs/10h_clients.ditto.ipynb #651849ef
def train(self: ClientDitto):
    self.model = self.model.to(self.device)
    self.model.train()
    for _ in range(self.cfg.local_epochs):
        for i, batch in enumerate(self.train_loader):
            batch = self.send_to_device(batch)
            X, y = batch[self.data_key], batch[self.label_key]
            output = self.model(X)
            loss = self.criterion(output, y)
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()

# %% ../../nbs/10h_clients.ditto.ipynb #d1449cba
def fit(self: ClientDitto):
    self.ptrain()
    self.train()
