"""The core abstraction for FedAvg client."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10f_clients.fedavg_ft.ipynb.

# %% auto #0
__all__ = ['ClientFedAvgFT']

# %% ../../nbs/10f_clients.fedavg_ft.ipynb #95d57626
from fastcore.utils import *
from fastcore.all import *

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

from .base_client import BaseClient
from ..utils.registery import AlgorithmRegistry

# %% ../../nbs/10f_clients.fedavg_ft.ipynb #c4456ff3
@AlgorithmRegistry.register_client("fedavg_ft")
class ClientFedAvgFT(BaseClient):
    def __init__(self,
                 id, # Unique identifier for the client
                 cfg, # A configuration object containing all the necessary parameters for training and evaluation.
                 train_loader, 
                 test_loader,
                 state, # A dictionary containing the model, optimizer and any changing component needed.
                 criterion,
                 device= None,
                 t= 0,
                 **kwargs # extra client-specific parameters (that cannot be passed in state and cfg), can be passed as here.
                 ):  
                 
        super().__init__(id, cfg, train_loader, test_loader, state, criterion, device, t, **kwargs)


# %% ../../nbs/10f_clients.fedavg_ft.ipynb #a9c754dd
@patch
def fine_tune(self: ClientFedAvgFT):
    
    self.model.to(self.device)
    self.model.train()
    for _ in range(self.cfg.algorithm.fine_tuning_epoch):
        for i, batch in enumerate(self.train_loader):
            self.optimizer.zero_grad()

            batch = self.send_to_device(batch)
            X, y = batch[self.data_key], batch[self.label_key]
            outputs = self.model(X)
            
            loss = self.criterion(outputs, y)
            loss.backward()
            self.optimizer.step()
