"""The implementation of FedProx client as in https://arxiv.org/pdf/2006.08848"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10e_clients.fedprox.ipynb.

# %% auto #0
__all__ = ['FedProxClient']

# %% ../../nbs/10e_clients.fedprox.ipynb #e189f8ff
import math
import os

from copy import deepcopy
from loguru import logger
from tqdm import tqdm

from fastcore.utils import patch
import torch
import torch.nn.functional as F

from .base_client import BaseClient
from ..utils.registery import AlgorithmRegistry

# %% ../../nbs/10e_clients.fedprox.ipynb #8d941e9e
@AlgorithmRegistry.register_client("fedprox")
class FedProxClient(BaseClient):
    def __init__(self,
                 id, # Unique identifier for the client
                 cfg, # A configuration object containing all the necessary parameters for training and evaluation.
                 train_loader, 
                 test_loader,
                 state, # A dictionary containing the model, optimizer and any changing component needed.
                 criterion,
                 device= None,
                 t= 0,
                 **kwargs # extra client-specific parameters (that cannot be passed in state and cfg), can be passed as here.
                 ):  
        
        super().__init__(id, cfg, train_loader, test_loader, state, criterion, device, t, **kwargs)
        
        self.global_params = deepcopy(list(self.model.parameters()))   

# %% ../../nbs/10e_clients.fedprox.ipynb #379ef57a
@patch
def fit(self: FedProxClient):
    
    self.model = self.model.to(self.device)
    self.local_model = self.local_model.to(self.device)
    self.model.train()
    self.local_model.train()
    for _ in range(self.cfg.local_epochs):
        for i, batch in enumerate(self.train_loader):
            batch = self.send_to_device(batch)
            X, y = batch[self.data_key], batch[self.label_key]
            outputs = self.model(X)
            self.optimizer.zero_grad()
            loss = self.criterion(outputs, y)
            loss.backward()
            self.optimizer.step(self.global_params, self.device)

