"""The core abstraction for FedPer client: https://arxiv.org/abs/1912.00818"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10h_clients.fedper.ipynb.

# %% auto #0
__all__ = ['ClientFedPer']

# %% ../../nbs/10h_clients.fedper.ipynb #95d57626
from fastcore.utils import *
from fastcore.all import *
import copy
import random
from typing import List, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Subset

from .base_client import BaseClient
from ..utils.registery import AlgorithmRegistry

# %% ../../nbs/10h_clients.fedper.ipynb #c4456ff3
@AlgorithmRegistry.register_client("fedper")
class ClientFedPer(BaseClient):
    def __init__(self,
                 id, # Unique identifier for the client
                 cfg, # A configuration object containing all the necessary parameters for training and evaluation.
                 train_loader, 
                 test_loader,
                 state, # A dictionary containing the model, optimizer and any changing component needed.
                 criterion,
                 device= None,
                 t= 0,
                 **kwargs # extra client-specific parameters (that cannot be passed in state and cfg), can be passed as here.
                 ):  
                 
        super().__init__(id, cfg, train_loader, test_loader, state, criterion, device, t, **kwargs)
        

# %% ../../nbs/10h_clients.fedper.ipynb #ff798610
@patch
def save_state(self: ClientFedPer, save_to_disk= False):

    client_state = {
        'model': self.model.state_dict(),
        'optimizer': self.optimizer.state_dict(),
    }

    if save_to_disk:
        state_path = os.path.join(self.cfg.server.save_dir, str(self.t), f"local_output_{self.id}", "state.pth")
        if not os.path.exists(os.path.dirname(state_path)):
            os.makedirs(os.path.dirname(state_path))
        torch.save(client_state, state_path)

    return client_state
        
