"""A graph laplacian-based algorithm introduced in https://arxiv.org/abs/2102.07148"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10e_clients.fedu.ipynb.

# %% auto #0
__all__ = ['ClientFedu']

# %% ../../nbs/10e_clients.fedu.ipynb #854971c4
from fastcore.utils import *
from fastcore.all import *
from loguru import logger

import torch
import torch.nn.functional as F

from .base_client import BaseClient
from ..utils.registery import AlgorithmRegistry

# %% ../../nbs/10e_clients.fedu.ipynb #f99f66af
@AlgorithmRegistry.register_client("fedu")
class ClientFedu(BaseClient):
    def __init__(self,
                 id, # Unique identifier for the client
                 cfg, # A configuration object containing all the necessary parameters for training and evaluation.
                 train_loader, 
                 test_loader,
                 state, # A dictionary containing the model, optimizer and any changing component needed.
                 criterion,
                 device= None,
                 t= 0,
                 **kwargs # extra client-specific parameters (that cannot be passed in state and cfg), can be passed as here.
                 ):  
        
        super().__init__(id, cfg, train_loader, test_loader, state, criterion, device, t, **kwargs)

