"""A graph laplacian-based algorithm introduced in https://arxiv.org/abs/2102.07148"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10e_clients.fedu.ipynb.

# %% auto #0
__all__ = ['ClientFedu']

# %% ../../nbs/10e_clients.fedu.ipynb #854971c4
from .base_client import BaseClient
from fastcore.utils import *
from fastcore.all import *
import os
import networkx as nx
import pickle
import json
from collections import defaultdict, OrderedDict
from copy import deepcopy
import random
from enum import Enum
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
from peft import *
from community import community_louvain
from ..utils import *
from ..client_selector import *
from ..optimizers import *
from tqdm import tqdm
import numpy as np
import pandas as pd
from loguru import logger
from ..utils import *
from ..metrics import *
from ..losses import *
from transformers import AutoTokenizer
from omegaconf.dictconfig import DictConfig
import numpy as np
import math


# %% ../../nbs/10e_clients.fedu.ipynb #f99f66af
class ClientFedu(BaseClient):
    def __init__(self,
                 id, # Unique identifier for the client
                 cfg, # A configuration object containing all the necessary parameters for training and evaluation.
                 train_loader, 
                 test_loader,
                 state, # A dictionary containing the model, optimizer and any changing component needed.
                 criterion,
                 device= None,
                 t= 0,
                 **kwargs # extra client-specific parameters (that cannot be passed in state and cfg), can be passed as here.
                 ):  
        
        super().__init__(id, cfg, train_loader, test_loader, state, criterion, device, t, **kwargs)

