"""The core abstraction for LG-FedAvg client: [https://arxiv.org/pdf/2001.01523](https://arxiv.org/pdf/2001.01523)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10h_clients.lgfedavg.ipynb.

# %% auto #0
__all__ = ['ClientLGFedAvg']

# %% ../../nbs/10h_clients.lgfedavg.ipynb #95d57626
from fastcore.utils import *
from fastcore.all import *
import copy
import random
from typing import List, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Subset

from .base_client import BaseClient
from ..utils.registery import AlgorithmRegistry

# %% ../../nbs/10h_clients.lgfedavg.ipynb #c4456ff3
@AlgorithmRegistry.register_client("lgfedavg")
class ClientLGFedAvg(BaseClient):
    def __init__(self,
                 id, # Unique identifier for the client
                 cfg, # A configuration object containing all the necessary parameters for training and evaluation.
                 train_loader, 
                 test_loader,
                 state, # A dictionary containing the model, optimizer and any changing component needed.
                 criterion,
                 device= None,
                 t= 0,
                 **kwargs # extra client-specific parameters (that cannot be passed in state and cfg), can be passed as here.
                 ):  
                 
        super().__init__(id, cfg, train_loader, test_loader, state, criterion, device, t, **kwargs)
        

# %% ../../nbs/10h_clients.lgfedavg.ipynb #f251b5b1
@patch
def fit(self: ClientLGFedAvg):
    
    self.local_model.to(self.device)
    self.global_head.to(self.device)
    self.local_model.train()
    self.global_head.train()
    for _ in range(self.cfg.local_epochs):
        for i, batch in enumerate(self.train_loader):
            self.optimizer.zero_grad()

            batch = self.send_to_device(batch)
            X, y = batch[self.data_key], batch[self.label_key]
            h = self.local_model(X)
            logits = self.global_head(h)

            loss = self.criterion(logits, y)
            loss.backward()
            self.optimizer.step()


# %% ../../nbs/10h_clients.lgfedavg.ipynb #fabab847
@patch
def train_test_stats(self: ClientLGFedAvg, batch: dict) -> tuple:
    metrics = {k: 0 for k in list(self.cfg.training_metrics)}  # Ensure metrics is always defined

    X, y = batch[self.data_key], batch[self.label_key]
    h = self.local_model(X)
    logits = self.global_head(h)
    loss = self.criterion(logits, y)
    y_pred = logits.argmax(dim=-1)
    y_true = batch[self.label_key]

    metrics = self.training_metrics.compute(y_pred= y_pred, y_true= y_true)

    return loss, metrics


# %% ../../nbs/10h_clients.lgfedavg.ipynb #03418c37
@patch
def evaluate_local(self: ClientLGFedAvg, loader= 'train') -> dict:
    total_loss = 0
    lst_metrics = []

    self.local_model = self.local_model.to(self.device)
    self.local_model.eval()
    self.global_head = self.global_head.to(self.device)
    self.global_head.eval()
    num_eval = 0
    data_loader = self.train_loader if loader == 'train' else self.test_loader
    
    with torch.no_grad():
        for i, batch in enumerate(data_loader):
            batch = self.send_to_device(batch)
            loss, metrics = self.train_test_stats(batch)                 
            if not math.isnan(loss.item()):
                total_loss += loss.item()  
                num_eval += len(batch[self.data_key])  # Ensure num_eval is updated
                lst_metrics.append(metrics)           
    
    avg_loss = total_loss / num_eval if num_eval > 0 else 0.0
    self.logger.info(f"Average {loader} Loss is : {avg_loss}")
    
    if lst_metrics:
        total_metrics = {k: sum(m.get(k, 0) for m in lst_metrics) / len(lst_metrics) for k in self.cfg.test_metrics}
    else:
        total_metrics = {k: 0.0 for k in self.cfg.test_metrics}

    self.logger.info(f"Average {loader} Metrics: {total_metrics}")
    return {"loss": avg_loss, "metrics": total_metrics}


# %% ../../nbs/10h_clients.lgfedavg.ipynb #91932e11
@patch
def save_state(self: ClientLGFedAvg, save_to_disk= False):  
    # save the model to self.cfg.save_dir/comm_round/f"local_output_{id}"/state.pth

    state_dict = {}
    state_dict['local_model'] = self.local_model.state_dict()
    state_dict['global_head'] = self.global_head.state_dict()
    state_dict['optimizer'] = self.optimizer.state_dict()

    if save_to_disk:
        state_path = os.path.join(self.cfg.server.save_dir, str(self.t), f"local_output_{self.id}", "state.pth")
        if not os.path.exists(os.path.dirname(state_path)):
            os.makedirs(os.path.dirname(state_path))

        torch.save(state_dict, state_path)

    return state_dict
