"""The implementation of pFedMe client as in https://arxiv.org/pdf/2006.08848"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/10c_clients.pfedme.ipynb.

# %% auto #0
__all__ = ['pFedMeClient']

# %% ../../nbs/10c_clients.pfedme.ipynb #e189f8ff
import math
import os

from copy import deepcopy
from loguru import logger
from tqdm import tqdm

from fastcore.utils import patch
import torch
import torch.nn.functional as F

from .base_client import BaseClient
from ..utils.registery import AlgorithmRegistry

# %% ../../nbs/10c_clients.pfedme.ipynb #8d941e9e
@AlgorithmRegistry.register_client("pfedme")
class pFedMeClient(BaseClient):
    def __init__(self,
                 id, # Unique identifier for the client
                 cfg, # A configuration object containing all the necessary parameters for training and evaluation.
                 train_loader, 
                 test_loader,
                 state, # A dictionary containing the model, optimizer and any changing component needed.
                 criterion,
                 device= None,
                 t= 0,
                 **kwargs # extra client-specific parameters (that cannot be passed in state and cfg), can be passed as here.
                 ):  
        
        super().__init__(id, cfg, train_loader, test_loader, state, criterion, device, t, **kwargs)
        
        
        self.local_params = deepcopy(list(self.model.parameters()))  
        self.personalized_params = deepcopy(list(self.model.parameters()))

# %% ../../nbs/10c_clients.pfedme.ipynb #379ef57a
@patch
def fit(self: pFedMeClient):
    
    self.model = self.model.to(self.device)
    self.model.train()
    for _ in range(self.cfg.local_epochs):
        for i, batch in enumerate(self.train_loader):
            batch = self.send_to_device(batch)
            # find an approximate theta
            for _ in range(self.cfg.algorithm.K):
                self.optimizer.zero_grad()
                X, y = batch[self.data_key], batch[self.label_key]
                outputs = self.model(X)
                
                loss = self.criterion(outputs, y)
                loss.backward()
                self.personalized_params = self.optimizer.step(self.local_params, self.device)

            # update local weight after finding aproximate theta
            with torch.no_grad():
                for new_param, localweight in zip(self.personalized_params, self.local_params):
                    localweight = localweight.to(self.device)
                    localweight.data = localweight.data - self.cfg.algorithm.lambda_ * self.cfg.optimizer.lr * (localweight.data - new_param.data)
                    
    self.update_parameters(self.model, self.local_params)

# %% ../../nbs/10c_clients.pfedme.ipynb #6eb7ef2f
@patch
def train_test_stats(self: pFedMeClient, batch: dict) -> tuple:
    metrics = {k: 0 for k in list(self.cfg.training_metrics)}  # Ensure metrics is always defined

    try:
        X, y = batch[self.data_key], batch[self.label_key]
        logits = self.model(X)
        loss = self.criterion(logits, y)
        probs = torch.nn.functional.softmax(logits, dim=-1)
        y_pred = probs.argmax(dim=-1)
        y_true = batch[self.label_key]

        metrics = self.training_metrics.compute(y_pred=y_pred, y_true=y_true)

    except Exception as e:
        print(f"Error in _closure Eval_test_stats: {e}")
        return torch.tensor(0.0, dtype=torch.float32, device=self.device), metrics  # Return safe values

    return loss, metrics


# %% ../../nbs/10c_clients.pfedme.ipynb #4cf8b8b0
@patch
def evaluate_local(self: pFedMeClient, loader= 'train'):
    self.personalized_params = [param.to(self.device) for param in self.personalized_params]
    self.local_params = [param.to(self.device) for param in self.local_params]
    self.update_parameters(self.model, self.personalized_params) if loader == 'test' else self.update_parameters(self.model, self.local_params)
    data_loader = self.train_loader if loader == 'train' else self.test_loader
    
    total_loss = 0
    lst_metrics = []
    num_eval = 0
    
    with torch.no_grad():
        for i, batch in enumerate(data_loader):
            batch = self.send_to_device(batch)
            loss, metrics = self.train_test_stats(batch)                 
            if not math.isnan(loss.item()):
                total_loss += loss.item()  
                num_eval += len(batch[self.data_key])  # Ensure num_eval is updated
                lst_metrics.append(metrics)           
    
    avg_loss = total_loss / num_eval if num_eval > 0 else 0.0
    self.logger.info(f"Average {loader} Loss is : {avg_loss}")
    
    if lst_metrics:
        total_metrics = {k: sum(m.get(k, 0) for m in lst_metrics) / len(lst_metrics) for k in self.cfg.test_metrics}
    else:
        total_metrics = {k: 0.0 for k in self.cfg.test_metrics}

    return {"loss": avg_loss, "metrics": total_metrics}

# %% ../../nbs/10c_clients.pfedme.ipynb #cf056640
@patch
def save_state(self: pFedMeClient, save_to_disk= False):

    client_state = {
        "model": self.model.state_dict(),
        'optimizer': self.optimizer.state_dict(),
        'local_params': [param.cpu() for param in self.local_params],
        'personalized_params':   [param.cpu() for param in self.personalized_params],
    }

    if save_to_disk:
        state_path = os.path.join(self.cfg.server.save_dir, str(self.t), f"local_output_{self.id}", "state.pth")
        if not os.path.exists(os.path.dirname(state_path)):
            os.makedirs(os.path.dirname(state_path))
        torch.save(client_state, state_path)

    return client_state
        
