"""The core abstraction for different FL Servers. Any general Server functionality resides here."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/11a_server.base_server.ipynb.

# %% auto #0
__all__ = ['StateManager', 'DiskStateManager', 'BaseServer']

# %% ../../nbs/11a_server.base_server.ipynb #95d57626
import gc
from fastcore.utils import patch

from tqdm import tqdm
from loguru import logger

import torch
import torch.nn as nn
import torch.nn.functional as F

from ..client_selector import BaseClientSelector
from ..data import prepare_dl
from ..models import create_model
from ..optimizers import get_optimizer

# %% ../../nbs/11a_server.base_server.ipynb #84ff3d97
class StateManager:
    def __init__(self):
        self.registry = {} 

    def set_state(self, client_id, state_dict):
        """
        Takes a dictionary of tensors/objects and moves them to CPU.
        Works for weights, optimizer states, anchors (h), etc.
        """
        if client_id not in self.registry:
            self.registry[client_id] = {}

        for key, value in state_dict.items():
            # Deep clone and move to CPU if it's a torch object
            if isinstance(value, torch.Tensor):
                self.registry[client_id][key] = value.detach().cpu().clone()
            elif isinstance(value, dict):
                # Handle nested dicts (like optimizer.state_dict())
                self.registry[client_id][key] = self._to_cpu(value)
            else:
                self.registry[client_id][key] = value

    def get_state(self, client_id):       
        if client_id not in self.registered_ids:
            init_state = {}
            return init_state
     
        return self.registry.get(client_id, {})

    def _to_cpu(self, obj):
        """Recursively moves tensors in a nested structure to CPU."""
        if isinstance(obj, torch.Tensor):
            return obj.detach().cpu().clone()
        elif isinstance(obj, dict):
            return {k: self._to_cpu(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [self._to_cpu(v) for v in obj]
        return obj

    @property
    def registered_ids(self):
        return list(self.registry.keys())

# %% ../../nbs/11a_server.base_server.ipynb #31703794
import torch

class DiskStateManager:
    def __init__(self, save_dir):
        self.save_dir = save_dir
        self.registry = {} 

    def set_state(self, client_id, state_dict):
        """
        Takes a dictionary of tensors/objects and moves them to CPU.
        Works for weights, optimizer states, anchors (h), etc.
        """
        if client_id not in self.registry:
            self.registry[client_id] = {}

        for key, value in state_dict.items():
            # Deep clone and move to CPU if it's a torch object
            if isinstance(value, torch.Tensor):
                self.registry[client_id][key] = value.detach().cpu().clone()
            elif isinstance(value, dict):
                # Handle nested dicts (like optimizer.state_dict())
                self.registry[client_id][key] = self._to_cpu(value)
            else:
                self.registry[client_id][key] = value

    def get_state(self, client_id):
        return self.registry.get(client_id, {})

    def _to_cpu(self, obj):
        """Recursively moves tensors in a nested structure to CPU."""
        if isinstance(obj, torch.Tensor):
            return obj.detach().cpu().clone()
        elif isinstance(obj, dict):
            return {k: self._to_cpu(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [self._to_cpu(v) for v in obj]
        return obj

# %% ../../nbs/11a_server.base_server.ipynb #c4456ff3
class BaseServer:
    def __init__(self,
                 cfg,
                 client_selector,
                 client_cls,
                 criterion,
                 fds,
                 writer= None,
                 device= None,
                 **kwargs
                 ):  
                 
        self.cfg = cfg 
        self.client_selector = client_selector
        self.client_cls = client_cls
        self.criterion = criterion
        self.writer = writer
        self.fds = fds
        self.device = device
        self.model = create_model(self.cfg)
        for key, value in kwargs.items():
            setattr(self, key, value)
        self.state_mgr = StateManager()
        self.logger = logger

# %% ../../nbs/11a_server.base_server.ipynb #e7538af5
@patch
def client_fn(self: BaseServer, id, comm_round, client_state):

    if comm_round == 1 and client_state == {}:
        client_state['model'] = self.model.state_dict()

    model = create_model(self.cfg)
    model.load_state_dict(client_state['model'])
    client_state['model'] = model

    optimizer = get_optimizer(self.cfg)(model.parameters(), lr= 0.001)#self.cfg.optimizer.lr)
    optimizer.load_state_dict(client_state['optimizer']) if 'optimizer' in client_state else None
    client_state['optimizer'] = optimizer

    train_loader = prepare_dl(self.cfg, id, self.fds, train=True, distributed=False)
    test_loader = prepare_dl(self.cfg, id, self.fds, train=False, distributed=False)
    client = self.client_cls(id= id, 
                             cfg= self.cfg,
                             train_loader= train_loader,
                             test_loader= test_loader,
                             state= client_state,
                             criterion= self.criterion,
                             device= self.device,
                             t= comm_round)
    client.logger = self.logger
    return client


# %% ../../nbs/11a_server.base_server.ipynb #1d4c83cb
@patch
def train(self: BaseServer):
    res =  []
    selected_clients = self.client_selector.select()
    
    for t in range(1, self.cfg.n_rounds + 1):
        lst_active_ids = selected_clients[t-1]
        len_clients_ds = {}

        for id in lst_active_ids:
            client_state = self.state_mgr.get_state(id)
            client = self.client_fn(id= id, comm_round= t, client_state= client_state)
            client.fit()
            self.logger.info(f"Client {id} finished training.")
            self.logger.info("*"*20)
            self.state_mgr.set_state(id, client.save_state())
            
            len_clients_ds[id] = len(client.train_loader.dataset)

            del client 
            gc.collect()
            torch.cuda.empty_cache()

        self.aggregate(lst_active_ids, t, len_clients_ds)
        train_res, test_res = self.evaluate(t)
        # self.state_mgr.registry.clear() if self.cfg.agg == "one_model" else None
        
        train_df, test_df = self.writer.write(lst_active_ids, train_res, test_res, t) 
        res.append((train_df, test_df))
        
    self.writer.save(res)
    self.writer.finish()

    return res

# %% ../../nbs/11a_server.base_server.ipynb #ce0e22b2
@patch
def aggregate(self: BaseServer):
    raise NotImplementedError("This method should be implemented by subclasses.")
        

# %% ../../nbs/11a_server.base_server.ipynb #19644a38
@patch
def evaluate(self: BaseServer, t):
    lst_train_res = []
    lst_test_res = []
    for id in range(self.cfg.num_clients):
        client_state = self.state_mgr.get_state(id)
        client = self.client_fn(id= id, comm_round= t, client_state= client_state)
        
        res_train = client.evaluate_local(loader= 'train')
        lst_train_res.append(res_train)

        res_test = client.evaluate_local(loader= 'test')
        lst_test_res.append(res_test)
        
        del client
        gc.collect()
        torch.cuda.empty_cache()

    return lst_train_res, lst_test_res    

