"""The core abstraction for `FedRep` server: [https://proceedings.mlr.press/v139/collins21a.html](https://proceedings.mlr.press/v139/collins21a.html)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/11h_server.fedrep.ipynb.

# %% auto #0
__all__ = ['ServerFedRep']

# %% ../../nbs/11h_server.fedrep.ipynb #95d57626
from fastcore.utils import *
from fastcore.all import *
import os

import copy
from tqdm import tqdm
from loguru import logger

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

from ..client_selector import BaseClientSelector
from ..data import prepare_dl
from ..models import create_model
from ..optimizers import get_optimizer

from .base_server import BaseServer
from ..utils.registery import AlgorithmRegistry
from ..core import get_clean_kwargs
from ..optimizers.custom_optimizers import PerturbedGradientDescent

# %% ../../nbs/11h_server.fedrep.ipynb #c4456ff3
@AlgorithmRegistry.register_server("fedrep")
class ServerFedRep(BaseServer):
    def __init__(self,
                 cfg,
                 client_selector,
                 client_cls,
                 criterion,
                 fds,
                 writer= None,
                 device= None,
                 **kwargs
                 ):  
                 
        super().__init__(cfg, client_selector, client_cls, criterion, fds, writer, device, **kwargs) 
                 

# %% ../../nbs/11h_server.fedrep.ipynb #3b779c4a
@patch
def client_fn(self: ServerFedRep, id, comm_round, client_state):

    if (comm_round == 1 and client_state == {}) or client_state == {}:
        client_state['backbone'] = self.model.backbone.state_dict()
        client_state['head'] = self.model.head.state_dict()

    backbone = create_model(self.cfg).backbone
    backbone.load_state_dict(client_state['backbone'])
    client_state['backbone'] = backbone

    head = create_model(self.cfg).head
    head.load_state_dict(client_state['head'])
    client_state['head'] = head

    
    kwargs = get_clean_kwargs(self.cfg.optimizer)
    kwargs.pop("cls", None)
    kwargs.pop("lr", None)
    g1 = {"params": client_state['backbone'].parameters(), "lr": self.cfg.algorithm.backbone_lr, **kwargs}
    g2 = {"params": client_state['head'].parameters(), "lr": self.cfg.algorithm.head_lr, **kwargs}
    optimizer = get_optimizer(self.cfg)([ g1, g2 ])
    optimizer.load_state_dict(client_state['optimizer']) if 'optimizer' in client_state else None
    for state in optimizer.state.values():
        for k, v in state.items():
            if isinstance(v, torch.Tensor):
                state[k] = v.to(self.device)

    client_state['optimizer'] = optimizer

    train_loader = prepare_dl(self.cfg.data, id, self.fds, train=True, distributed=False)
    test_loader = prepare_dl(self.cfg.data, id, self.fds, train=False, distributed=False)
    client = self.client_cls(id= id, 
                             cfg= self.cfg,
                             train_loader= train_loader,
                             test_loader= test_loader,
                             state= client_state,
                             criterion= self.criterion,
                             device= self.device,
                             t= comm_round)
    client.logger = self.logger
    return client


# %% ../../nbs/11h_server.fedrep.ipynb #ce0e22b2
@patch
def aggregate(self: ServerFedRep, lst_active_ids, comm_round, len_clients_ds):
    m_t = sum(len_clients_ds.values())
    
    with torch.no_grad():
        global_model = None
        
        for id in lst_active_ids:
            client_state_dict = self.state_mgr.get_state(id).get('backbone', None)

            if global_model is None:
                global_model = {k: torch.zeros_like(v) for k, v in client_state_dict.items()}

            n_k = len_clients_ds[id]
            weight = n_k / m_t
            for key in global_model.keys():
                global_model[key].add_(client_state_dict[key], alpha=weight)

        self.model.backbone.load_state_dict(global_model)
        
        for id in lst_active_ids:
            self.state_mgr.set_state(id, {
                    'backbone': self.model.backbone.state_dict(),
                    'head': self.state_mgr.get_state(id).get('head', None),
                    'optimizer': self.state_mgr.get_state(id).get('optimizer', None),
            })
        
