"""A graph laplacian-based algorithm introduced in https://arxiv.org/abs/2102.07148"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/11i_servers.fedu.ipynb.

# %% auto #0
__all__ = ['ServerFedu']

# %% ../../nbs/11i_servers.fedu.ipynb #854971c4
from fastcore.utils import *
from fastcore.all import *
import os

import torch
import torch.nn.functional as F


from tqdm import tqdm
import numpy as np
import pandas as pd
from loguru import logger

import math

from .base_server import BaseServer
from ..utils.registery import AlgorithmRegistry

# %% ../../nbs/11i_servers.fedu.ipynb #f99f66af
@AlgorithmRegistry.register_server("fedu")
class ServerFedu(BaseServer):
    def __init__(self,
                 cfg,
                 client_selector,
                 client_cls,
                 criterion,
                 fds,
                 writer= None,
                 device= None,
                 **kwargs
                 ):  
                 
        super().__init__(cfg, client_selector, client_cls, criterion, fds, writer, device, **kwargs) 

        np.random.seed(self.cfg.random_seed)
        b = np.random.uniform(0,1,size=(self.cfg.num_clients, self.cfg.num_clients))
        b_symm = (b + b.T)/2
        b_symm[b_symm < 0.25] = 0
        self.alk_connection = b_symm

# %% ../../nbs/11i_servers.fedu.ipynb #bc01f93d
@patch
def aggregate(self: ServerFedu, lst_active_ids, comm_round, len_clients_ds):

    global_lr = float(self.cfg.optimizer.lr) * float(self.cfg.local_epochs)
    reg_param = self.cfg.algorithm.lambda_
    
    with torch.no_grad():
        aggregated_states = []
        for i, id in enumerate(lst_active_ids):
            client_state = self.state_mgr.get_state(id)
            client_state_dict = client_state['model']

            client_diff = {
                key: torch.zeros_like(value) 
                for key, value in client_state_dict.items()
            }
            
            for j, other_id in enumerate(lst_active_ids):
                if i == j:
                    continue
                other_state_dict = self.state_mgr.get_state(other_id).get('model', None)

                weight = self.alk_connection[int(id)][int(other_id)]
                for key in client_state_dict.keys():
                    if not client_state_dict[key].is_floating_point():
                        continue
                    client_diff[key].add_(weight * (client_state_dict[key] - other_state_dict[key]))

            for key in client_state_dict:
                if not client_state_dict[key].is_floating_point():
                    continue
                client_state_dict[key].sub_(global_lr * reg_param * client_diff[key])

            clinet_state = {
                    'model': client_state_dict,
                    'optimizer': client_state['optimizer'],
                }
            aggregated_states.append(clinet_state)

        for i, id in enumerate(lst_active_ids):
            self.state_mgr.set_state(id, aggregated_states[i])
