"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/02h_models.vision.ipynb.

# %% auto #0
__all__ = ['create_model']

# %% ../../../nbs/02h_models.vision.ipynb #5ce10414
from typing import Optional, Any
import torch.nn as nn
from .registery import *
from .lenets import make_lenet
from .resnets import make_resnet
from .mobilenets import make_mobilenetv3
from .efficientnets import make_efficientnet
from .vits import make_vit

# %% ../../../nbs/02h_models.vision.ipynb #a8a030fc
def create_model(
    name: str,
    pretrained: bool = False,
    num_classes: int = 10,
    **kwargs
) -> nn.Module:
    """
    Create a vision model.
    
    Args:
        name: Model architecture and variant separated by underscore (e.g., 'resnet_50', 'vit_base')
        pretrained: Whether to load pretrained weights
        num_classes: Number of output classes
        **kwargs: Additional model-specific arguments
    
    Returns:
        Initialized model
    
    Examples:
        >>> model = create_model('resnet_50', num_classes=1000)
        >>> model = create_model('vit_base', num_classes=10, pretrained=True)
    """
    architecture, variant = parse_model_name(name)
    factory = get_factory(architecture)
    
    return factory(
        variant=variant,
        pretrained=pretrained,
        num_classes=num_classes,
        **kwargs
    )

# %% ../../../nbs/02h_models.vision.ipynb #dc9f01ae
__all__ = [
    'create_model',
    'list_models',
    'list_model_names',
    'make_resnet',
    'make_vit',
    'make_mobilenetv3',
    'make_efficientnet',
]
