"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/07_vision.models.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/07_vision.models.ipynb 3
from fastcore.utils import *  # noqa: F403
from torch import nn
from peft import *  # noqa: F403
