"""A unified API for Vision datasets."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/01b_data.vision.VisionBlock.ipynb.

# %% auto #0
__all__ = ['RotateMaskTransform', 'VisionBlock']

# %% ../../../nbs/01b_data.vision.VisionBlock.ipynb #bea53ac2
import numpy as np
import matplotlib.pyplot as plt
from fastcore.utils import *
import torch
from torchvision.transforms import v2
import torch.nn as nn

# %% ../../../nbs/01b_data.vision.VisionBlock.ipynb #ffb4516c
class RotateMaskTransform(torch.nn.Module):
    def __init__(self, rotation_k, mask, patch_size, cfg):
        super().__init__()
        self.k = rotation_k
        self.mask = torch.tensor(mask, dtype=torch.float32).unsqueeze(0)
        self.patch_size = patch_size
        self.cfg = cfg

    def forward(self, img):
        """
        Applies the following transformations to the input image:
        1. Rotate the image by 90 degrees k times.
        2. Apply a mask to the rotated image, if patch_size > 0.
        3. Normalize the image using the mean and std from the data configuration.

        Args:
            img (PIL Image): The input image to be transformed.
        Returns:
            torch.Tensor: The transformed image tensor.
        """

        img_tensor = v2.functional.to_image(img)
        img_tensor = v2.functional.to_dtype(img_tensor, dtype=torch.float32, scale=True)
        img_rot = torch.rot90(img_tensor, k=self.k, dims=[1,2]) 

        if self.patch_size > 0:
            img_masked = torch.max(img_rot, self.mask)
        else:
            img_masked = img_rot

        m_min, m_max = img_masked.min(), img_masked.max()
        if m_max > m_min:
            img_masked = (img_masked - m_min) / (m_max - m_min)

            
        img_normalized = v2.functional.normalize(
            img_masked, 
            mean=self.cfg.mean, 
            std=self.cfg.std
        )
        return img_normalized

# %% ../../../nbs/01b_data.vision.VisionBlock.ipynb #ae61c73d
class VisionBlock(torch.utils.data.Dataset):
    def __init__(self, cfg, idx, fds, train=True, transform=None, seed= 42):
        self.cfg = cfg
        self.seed = seed
        split = "train"
            
        self.data = fds.load_partition(partition_id=idx, split=split)
        self.x_key = self.cfg.x
        self.y_key = self.cfg.y
        
        
        def build_transform(transform= None):
            if self.cfg.name == "mnist_rotated_batched":
                transform = RotateMaskTransform(
                    rotation_k=self.data.rotation_k, 
                    mask=self.data.silo_mask,
                    patch_size=2,
                    cfg=self.cfg
                )
            
            elif not transform:
                transform = v2.Compose([
                    v2.ToImage(),            # 2. Convert to Tensor (H,W,C -> C,H,W)
                    v2.ToDtype(torch.float32, scale=True),
                    v2.Normalize(self.cfg.mean, self.cfg.std)
                ]) 
            elif transform:
                transform = transform

            else:
                raise ValueError("""Please provide a valid transform to handle the dataset. See `fedai.data.data` module.""")
            
            return transform

        def apply_transforms(batch):
            batch[self.x_key] = [
                self.transform(img).as_subclass(torch.Tensor) 
                for img in batch[self.x_key]
            ]
            return batch

        partition_train_test = self.data.train_test_split(test_size=0.2, seed= self.seed)
        self.selected_partition = partition_train_test["train"] if train else partition_train_test["test"]

        self.transform = build_transform(transform)
        self.partition = self.selected_partition.with_transform(apply_transforms)

    def __getitem__(self, idx):        
        x = self.partition[idx][self.x_key]
        y = self.partition[idx][self.y_key]
        return {'image': x, 'label': y}

    def __len__(self):
        return len(self.partition)
