# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fedai',
                'doc_host': 'https://Ahmed-Khaled-Saleh.github.io',
                'git_url': 'https://github.com/Ahmed-Khaled-Saleh/fedai',
                'lib_path': 'fedai'},
  'syms': {'fedai.core': {'fedai.core.foo': ('core.html#foo', 'fedai/core.py')}}}
