"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['get_clean_kwargs']

# %% ../nbs/00_core.ipynb #39fcf9b9-6f5e-4684-b274-699c60f841d2
from dataclasses import is_dataclass, asdict
from omegaconf import DictConfig, OmegaConf

# %% ../nbs/00_core.ipynb #91c409ad-0ac7-4db4-a0e3-1b4c7bec3cfe
def get_clean_kwargs(obj):
    if isinstance(obj, DictConfig):
        return OmegaConf.to_container(obj, resolve=True)
    
    elif is_dataclass(obj):
        return asdict(obj)
    
    elif isinstance(obj, dict):
        return obj.copy()
        
    return {}
