"""utils used by the learner class"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_learner_utils.ipynb.

# %% auto #0
__all__ = ['get_cls', 'get_criterion', 'load_state_from_disk']

# %% ../nbs/10_learner_utils.ipynb #8633aaf3
import os
import random
from copy import deepcopy
import numpy as np
import torch.nn as nn
import torch
from .models import * 


# %% ../nbs/10_learner_utils.ipynb #222f8c43
import importlib
def get_cls(module_name, class_name):
    module = importlib.import_module(module_name)
    return getattr(module, class_name)

# %% ../nbs/10_learner_utils.ipynb #c7441ee7
def get_criterion(customm_fn):
    if customm_fn:
        return customm_fn
    else:
        return nn.CrossEntropyLoss()

# %% ../nbs/10_learner_utils.ipynb #a3eebcd0
def load_state_from_disk(cfg, state, latest_round, id, t, state_dir):

    
    if cfg.agg == "one_model":
        global_model_path = os.path.join(cfg.save_dir, str(t-1), "global_model", "state.pth")
        gloabal_model_state = torch.load(global_model_path, weights_only= False)

        if isinstance(state["model"], torch.nn.Module) or isinstance(state["model"], dict) :
            state["model"].load_state_dict(gloabal_model_state["model"])
            print(f"Loaded Global model state from {global_model_path}")

        else:
            set_peft_model_state_dict(state["model"], gloabal_model_state["model"], "default")  # type: ignore

    else:

        if id not in latest_round:
            if cfg.client_cls == "pFedMe":
                state["pers_model"] = deepcopy(state['model'])
            return state
        
        latest_comm_round = latest_round[id]
        
        old_state_path = os.path.join(cfg.save_dir, str(latest_comm_round), f"{state_dir}{id}", "state.pth")
        old_saved_state = torch.load(old_state_path, weights_only= False)

        if isinstance(state["model"], nn.Module) or isinstance(state["model"], dict) :
            state["model"].load_state_dict(old_saved_state["model"])

            if cfg.client_cls == "DMTL":
                state["h_c"] = old_saved_state["h_c"]
                state["h"] = state["h_c"]

            if cfg.client_cls == "pFedMe":
                state["pers_model"] = deepcopy(state['model'])
                state["pers_model"].load_state_dict(old_saved_state["pers_model"])
                print(f"Personnalized model loaded from {old_state_path}")
            
            print(f"Loaded client model state from {old_state_path}")
        else:
            set_peft_model_state_dict(state["model"], old_saved_state["model"], "default") # type: ignore

    return state
