"""ِAny custom losses should be here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_losses.ipynb.

# %% auto #0
__all__ = ['AnchorLoss']

# %% ../nbs/03_losses.ipynb #1d297c19
import copy
import numpy as np
import torch, os, random
import torch.nn as nn
import torch.nn.functional as F
from fastcore.utils import *
from copy import deepcopy

# %% ../nbs/03_losses.ipynb #7ba8067f
class AnchorLoss(nn.Module):
    def __init__(self, random_seed, num_classes, hidden_dim, t=1, h_c=None):
        super().__init__()
        self.num_classes = num_classes
        torch.manual_seed(random_seed)  
        np.random.seed(random_seed)
        random.seed(random_seed)
        
        # Initialize anchor on CPU first
        self.anchor = nn.Parameter(F.normalize(torch.randn(num_classes, hidden_dim)))
        
        if t > 1 and h_c is not None:
            # copy_ works regardless of device as long as we use no_grad
            with torch.no_grad():
                self.anchor.copy_(h_c)

    def forward(self, feature, _target, Lambda=0.1):
        device = feature.device # Follow the lead of the input features
        
        # Ensure anchor and target are where they need to be
        anchors = self.anchor.to(device)
        _target = _target.long().to(device)

        # index_select on the correct device
        centre = anchors.index_select(dim=0, index=_target)
        
        # Use bincount instead of histc - it's faster and GPU-native
        counter = torch.bincount(_target, minlength=self.num_classes).float()
        count = counter[_target]
        
        # Math operations
        centre_dis = feature - centre
        dis_ = torch.pow(centre_dis, 2).sum(dim=1) / count.clamp(min=1)
        
        return Lambda * (dis_.sum() / self.num_classes)
