# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_metrics.ipynb.

# %% auto 0
__all__ = ['Metrics']

# %% ../nbs/07_metrics.ipynb 2
from fastcore.utils import *

# %% ../nbs/07_metrics.ipynb 3
import numpy as np
import torch
from rouge import Rouge
import evaluate

# %% ../nbs/07_metrics.ipynb 5
class Metrics:
    def __init__(self, names: list):
        self.metrics_names = names
        def validate_names(names):
            if len(names) == 0:
                return True
            try:
                evaluate.combine(names)
                return True
            except Exception as e:
                print(e)
                return False
        is_valid = validate_names(self.metrics_names)
        if not is_valid:
            raise ValueError(f"Invalid metric names, the available metrics are {evaluate.list_evaluation_modules('metric')}")

# %% ../nbs/07_metrics.ipynb 6
@patch
def compute(self:Metrics, y_true, y_pred, **kwargs):
    self.metrics = evaluate.combine(self.metrics_names)
    return self.metrics.compute(predictions= y_pred, references= y_true, **kwargs)
