"""Basic Model redirections happen here. You define a model, and call a get_model function from this notebook. After that, the notebook redirectes the model to the correct model type."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_models.ipynb.

# %% auto 0
__all__ = ['LogisticRegression', 'MLP']

# %% ../nbs/06_models.ipynb 3
from fastcore.utils import *  # noqa: F403
from transformers import AutoModelForCausalLM
import torch
from torch import nn
from peft import *  # noqa: F403
from .vision.models import *  # noqa: F403
from .text.models import *  # noqa: F403

# %% ../nbs/06_models.ipynb 4
class LogisticRegression(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_dim, num_classes)

    def forward(self, x):
        return self.linear(x)

# %% ../nbs/06_models.ipynb 5
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes):
        super(MLP, self).__init__()
        self.layer_input = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout()
        self.layer_hidden = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x = x.view(-1, x.shape[1]*x.shape[-2]*x.shape[-1])
        x = self.layer_input(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.layer_hidden(x)
        return x
