"""This module provides a registry for servers and clients algorithms. It allows for easy registration and retrieval of algorithms by name."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05a_utils.registery.ipynb.

# %% auto #0
__all__ = ['AlgorithmRegistry']

# %% ../../nbs/05a_utils.registery.ipynb #662a7b9c
class AlgorithmRegistry:
    CLIENTS = {}
    SERVERS = {}

    @classmethod
    def register_client(cls, name):
        def decorator(subclass):
            cls.CLIENTS[name.lower()] = subclass
            return subclass
        return decorator

    @classmethod
    def register_server(cls, name):
        def decorator(subclass):
            cls.SERVERS[name.lower()] = subclass
            return subclass
        return decorator

    @classmethod
    def get_classes(cls, name):
        """Returns both classes for a specific algorithm."""
        name = name.lower()
        if name not in cls.CLIENTS or name not in cls.SERVERS:
            raise KeyError(f"Algorithm '{name}' not fully registered. "
                           f"Clients: {list(cls.CLIENTS.keys())}, "
                           f"Servers: {list(cls.SERVERS.keys())}")
        return cls.CLIENTS[name], cls.SERVERS[name]
    

    def list_algorithms(cls):
        """Lists all registered algorithms."""
        return list(cls.CLIENTS.keys())
