"""Various Algorithm-specific params."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/7a_cfgs.algos.ipynb.

# %% auto #0
__all__ = ['AlgorithmConfig', 'FedAvgConfig', 'FedAvgFTConfig', 'FedUConfig', 'pFedMeConfig', 'SFMTLConfig', 'FedProxConfig',
           'DittoConfig', 'PerFedAvgConfig', 'APFLConfig', 'FedALA', 'IFCAConfig', 'FedPerConfig', 'LGFedAvgConfig',
           'FedRepConfig', 'FedRodConfig', 'FedBabuConfig', 'FedGPFLConfig', 'FedDBEConfig']

# %% ../../nbs/7a_cfgs.algos.ipynb #f725b3f6
from fastcore.utils import *
import pandas as pd
import wandb
import os
import argparse
import numpy as np
from dataclasses import dataclass
from typing import List, Optional


# %% ../../nbs/7a_cfgs.algos.ipynb #91b83577
@dataclass
class AlgorithmConfig:
    name: str


@dataclass
class FedAvgConfig(AlgorithmConfig):
    name: str = "fedavg"
    server_momentum: float = 0.0 


@dataclass
class FedAvgFTConfig(AlgorithmConfig):
    name: str = "fedavg_ft"
    fine_tuning_epochs: int = 5
    server_momentum: float = 0.0  



@dataclass
class FedUConfig(AlgorithmConfig):
    name: str = "fedu"
    lambda_: float = 0.03



@dataclass
class pFedMeConfig(AlgorithmConfig):
    name: str = "pfedme"
    K: int = 5
    lambda_: float = 10
    beta: float = 1.0

@dataclass
class SFMTLConfig(AlgorithmConfig):
    name: str = "sfmtl"
    m: float = 1.0
    lambda_: float = 0.03
    alpha: float = 0.49
    lambda_anchor: float = 0.1
    momentum_anchor: float = 0.5
    graph_type: str = "similarity"


@dataclass
class FedProxConfig(AlgorithmConfig):
    name: str = "fedprox"
    mu: float = 0.1


@dataclass
class DittoConfig(AlgorithmConfig):
    name: str = "ditto"
    mu: float = 0.005


@dataclass
class PerFedAvgConfig(AlgorithmConfig):
    name: str = "perfedavg"
    beta: float = 0.005



@dataclass
class APFLConfig(AlgorithmConfig):
    name: str = "apfl"
    alpha: float = 0.25


@dataclass
class FedALA(AlgorithmConfig):
    name: str = "fedala"
    rand_percent: int = 80
    layer_idx: int = 2
    eta: float = 1.0


@dataclass
class IFCAConfig(AlgorithmConfig):
    name: str = "ifca"
    K: int = 4


@dataclass
class FedPerConfig(AlgorithmConfig):
    name: str = "fedper"

@dataclass
class LGFedAvgConfig(AlgorithmConfig):
    name: str = "lgfedavg"
    local_lr : float = 0.05
    global_lr : float = 0.05

@dataclass
class FedRepConfig(AlgorithmConfig):
    name: str = "fedrep"
    plocal_epochs: int = 5
    backbone_lr : float = 0.05
    head_lr : float = 0.05

@dataclass
class FedRodConfig(AlgorithmConfig):
    name: str = "fedrod"
    model_lr : float = 0.05
    head_lr : float = 0.05

@dataclass
class FedBabuConfig(AlgorithmConfig):
    name: str = "fedbabu"
    fine_tuning_epochs: int = 5

@dataclass
class FedGPFLConfig(AlgorithmConfig):
    name: str = "gpfl"
    gce_lr : float = 0.005
    coV_lr : float = 0.005
    lamda : float = 0.1

@dataclass
class FedDBEConfig(AlgorithmConfig):
    name: str = "feddbe"
    kl_weight: float = 50.0
    momentum: float = 1.0
