"""Various Algorithm-specific params."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/7a_cfgs.algos.ipynb.

# %% auto #0
__all__ = ['AlgorithmConfig', 'FedAvgConfig', 'FedAvgFTConfig', 'FedUConfig', 'pFedMeConfig', 'SFMTLConfig', 'FedProxConfig',
           'DittoConfig', 'PerFedAvgConfig']

# %% ../../nbs/7a_cfgs.algos.ipynb #f725b3f6
from fastcore.utils import *
import pandas as pd
import wandb
import os
import argparse
import numpy as np
from dataclasses import dataclass
from typing import List, Optional


# %% ../../nbs/7a_cfgs.algos.ipynb #91b83577
@dataclass
class AlgorithmConfig:
    name: str


@dataclass
class FedAvgConfig(AlgorithmConfig):
    name: str = "fedavg"
    server_momentum: float = 0.0 


@dataclass
class FedAvgFTConfig(AlgorithmConfig):
    name: str = "fedavg_ft"
    server_momentum: float = 0.0  



@dataclass
class FedUConfig(AlgorithmConfig):
    name: str = "fedu"
    lambda_: float = 0.03



@dataclass
class pFedMeConfig(AlgorithmConfig):
    name: str = "pfedme"
    K: int = 5
    lambda_: float = 15
    personal_lr: float = 0.01
    beta: float = 1.0

@dataclass
class SFMTLConfig(AlgorithmConfig):
    name: str = "sfmtl"
    m: float = 1.0
    lambda_: float = 0.03
    alpha: float = 0.49
    lambda_anchor: float = 0.1
    momentum_anchor: float = 0.5
    graph_type: str = "similarity"


@dataclass
class FedProxConfig(AlgorithmConfig):
    name: str = "fedprox"
    mu: float = 0.1


@dataclass
class DittoConfig(AlgorithmConfig):
    name: str = "ditto"
    mu: float = 0.005


@dataclass
class PerFedAvgConfig(AlgorithmConfig):
    name: str = "perfedavg"
    beta: float = 0.005


