"""Basic configs for data sets."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/7c_cfgs.data.ipynb.

# %% auto #0
__all__ = ['DataConfig', 'VisionDataConfig', 'FederatedVisionDataConfig', 'CIFAR10Config', 'CIFAR100Config', 'MNISTConfig',
           'MNISTRotatedPatchedConfig', 'FashionMNISTConfig', 'TinyImageNetConfig']

# %% ../../nbs/7c_cfgs.data.ipynb #f725b3f6
from fastcore.utils import *
import pandas as pd
import numpy as np
from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict, Any
from .partitioners import *

# %% ../../nbs/7c_cfgs.data.ipynb #91b83577
@dataclass
class DataConfig:
    name: str
    modality: str
    batch_size: int = 128

@dataclass
class VisionDataConfig(DataConfig):
    modality: str = 'Vision'
    x : str = 'x'
    img_size: Tuple[int, int, int] = (3, 32, 32) 

@dataclass
class FederatedVisionDataConfig(VisionDataConfig):
    partitioner: Optional[PartitionerConfig] = field(default_factory=PathologicalConfig)
    hf_name: Optional[str] = None


@dataclass
class CIFAR10Config(FederatedVisionDataConfig):
    name: str = 'cifar10'
    num_classes: int = 10
    hf_name: str = 'uoft-cs/cifar10'
    classes: List[str] = field(default_factory=lambda: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck'])
    x:  str = 'img'
    y: str = 'label'
    mean: Tuple[float] = (0.4914, 0.4822, 0.4465)
    std: Tuple[float] = (0.2023, 0.1994, 0.2010)


@dataclass
class CIFAR100Config(CIFAR10Config):
    name: str = 'cifar100'
    num_classes: int = 100
    hf_name: str = 'uoft-cs/cifar100'
    classes: List[str] = field(default_factory=lambda: [f'class_{i}' for i in range(20)])
    y: str = 'coarse_label'
    mean: Tuple[float] = (0.5071, 0.4865, 0.4409)
    std: Tuple[float] = (0.2673, 0.2564, 0.2762)


@dataclass
class MNISTConfig(FederatedVisionDataConfig):
    name: str = 'mnist'
    num_classes: int = 10
    hf_name: str = 'ylecun/mnist'
    img_size: Tuple[int, int, int] = (1, 28, 28)
    partitioner: Optional[PartitionerConfig] = field(default_factory=PathologicalConfig)
    classes: List[str] = field(default_factory=lambda: [str(i) for i in range(10)])
    x:  str = 'image'
    y: str = 'label'
    mean: Tuple[float] = (0.1307,)
    std: Tuple[float] = (0.3081,)


@dataclass
class MNISTRotatedPatchedConfig(MNISTConfig):
    name: str = 'mnist_rotated_batched'
    partitioner: Optional[PartitionerConfig] = field(default_factory=RotatedBatchedConfig)
    

@dataclass
class FashionMNISTConfig(FederatedVisionDataConfig):
    name: str = 'fashionmnist'
    num_classes: int = 10
    hf_name: str = 'zalando-datasets/fashion_mnist'
    img_size: Tuple[int, int, int] = (1, 28, 28)
    classes: List[str] = field(default_factory=lambda: ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot'])
    x:  str = 'image'
    y: str = 'label'
    mean: Tuple[float] = (0.2860,)
    std: Tuple[float] = (0.3530,)

@dataclass
class TinyImageNetConfig(FederatedVisionDataConfig):
    name: str = 'tinyimagenet'
    num_classes: int = 200
    hf_name: str = 'zh-plus/tiny-imagenet'
    classes: List[str] = field(default_factory=lambda: [f'class_{i}' for i in range(200)])
    x:  str = 'image'
    y: str = 'label'
    mean: Tuple[float] = (0.4802, 0.4481, 0.3975)
    std: Tuple[float] = (0.2302, 0.2265, 0.2262)

