"""Basic configs for instantiating models."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/7d_cfgs.models.ipynb.

# %% auto #0
__all__ = ['VisionModelConfig', 'LeNetConfig', 'ResNetConfig', 'MobileNetConfig', 'EfficientNetConfig', 'ViTConfig']

# %% ../../nbs/7d_cfgs.models.ipynb #f725b3f6
from fastcore.utils import *
import pandas as pd
import wandb
import os
import argparse
import numpy as np
from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict, Any, Union, Literal


# %% ../../nbs/7d_cfgs.models.ipynb #26137ab1
@dataclass
class VisionModelConfig:
    name: str
    pretrained: bool= False
    num_classes: int= 10

@dataclass
class LeNetConfig(VisionModelConfig):
    name: str= 'lenet_fedavg'
    img_size: Tuple[int, int, int] = (1, 28, 28)
    hidden_dim: int = 512
    
@dataclass
class ResNetConfig(VisionModelConfig):
    name: str = "resnet_18"
    num_classes: int = 200
    preactivation: bool = True
    hidden_dim: int = 512
    img_size: Tuple[int, int, int] = (3, 32, 32)

@dataclass
class MobileNetConfig(VisionModelConfig):
    name: str = 'mobilenetv3_small'
    img_size: Tuple[int, int, int] = (3, 32, 32)

@dataclass
class EfficientNetConfig(VisionModelConfig):
    name: str = 'efficientnet_b0' 

@dataclass
class ViTConfig(VisionModelConfig):
    name: str = 'vit_small'
    num_classes: int = 200
    img_size: Tuple[int, int, int] = (3, 64, 64)
    patch_size: int = 4
    hidden_dim: int = 512
    depth: int = 6
    heads: int = 3
    mlp_dim: int = 1024
    pool: str = 'cls'
    dropout: float = 0.1
    emb_dropout: float = 0.1

