"""Entry point for configuration optimizers."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/7e_cfgs.optimizers.ipynb.

# %% auto #0
__all__ = ['BaseOptimizerConfig', 'PerFedavgOptimizerConfig', 'pFedMeOptimizerConfig', 'FedProxOptimizerConfig',
           'APFLOptimizerConfig']

# %% ../../nbs/7e_cfgs.optimizers.ipynb #f725b3f6
from fastcore.utils import *
from dataclasses import dataclass, field
from omegaconf import OmegaConf, MISSING
from typing import List, Optional, Tuple, Dict, Any, Union, Literal, Any


# %% ../../nbs/7e_cfgs.optimizers.ipynb #5fea4c4f
@dataclass
class BaseOptimizerConfig:
    cls: str = "SGD"
    lr: float = 0.001


@dataclass
class PerFedavgOptimizerConfig(BaseOptimizerConfig):
    cls: str = "PerFedAvgOpt"

@dataclass
class pFedMeOptimizerConfig(BaseOptimizerConfig):
    cls: str = "pFedMeOptimizer"
    lambda_: float = 0.1
    mu: float = 0.001

@dataclass
class FedProxOptimizerConfig(BaseOptimizerConfig):
    cls: str = "PerturbedGradientDescent"
    mu: float = 0.0

@dataclass
class APFLOptimizerConfig(BaseOptimizerConfig):
    cls: str = "APFLOptimizer"

