"""Basic confgis for different base partitioners."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/7b_cfgs.partitioners.ipynb.

# %% auto #0
__all__ = ['PartitionerConfig', 'PathologicalConfig', 'DirichletConfig', 'SizePartitionerConfig', 'RotatedBatchedConfig']

# %% ../../nbs/7b_cfgs.partitioners.ipynb #f725b3f6
from fastcore.utils import *
from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict, Any, Union, Literal
from enum import Enum
from flwr_datasets.partitioner import *
from ..data.vision.partitioners import *   

# %% ../../nbs/7b_cfgs.partitioners.ipynb #91b83577
@dataclass
class PartitionerConfig:
    cls: Optional[str] = None
    
@dataclass
class PathologicalConfig(PartitionerConfig):
    cls: str = "PathologicalPartitioner"
    num_partitions: int = 20
    partition_by: str = 'label'
    num_classes_per_partition: int = 2
    class_assignment_mode: str = "random" # deterministic
    
@dataclass
class DirichletConfig(PartitionerConfig):
    cls: str = "DirichletPartitioner"
    num_partitions: int = 20
    partition_by: str = 'label'
    alpha: float = 0.5

@dataclass
class SizePartitionerConfig(PartitionerConfig):
    cls: str = "SizePartitioner"
    partition_sizes: List[int] = field(default_factory=lambda: [1500, 2000])

@dataclass
class RotatedBatchedConfig(PartitionerConfig):
    cls: str = "RotatedPatchedPartitioner"
    num_partitions: int = 20
    num_rotations: int = 4
    patch_size: int = 2

