version: 1.0
project_name: example_project
logging_level: INFO
random_seed: 42
num_clients: 20

# Data configuration
data:
  dir_path: data
  batch_size: 10
  name: CIFAR10
  niid: false
  balance: false
  partitioner: DirPartitioner
  alpha: 0.1
  train_ratio: 0.75
  num_classes: 2

# Model configuration
model:
  name: MyModel
  type: transformer
  num_layers: 12
  hidden_size: 768
  dropout_rate: 0.1
