version: 1.0
project_name: example_project
logging_level: INFO
random_seed: 42
num_clients: 20
n_rounds: 10
m: 0.1
local_epochs: 2
lr: 0.01
save_dir : models
log_dir: logs

training_metrics: [accuracy]
test_metrics: [accuracy]
grad_norm_clip: 1.0

  
# Data configuration
data:
  dir_path: data
  modality: [Vision]
  batch_size: 10
  name: CIFAR10
  niid: false
  balance: false
  partitioner: DirPartitioner
  alpha: 0.1
  train_ratio: 0.75
  num_classes: 2


# Model configuration
model:
  dim_in: 784
  dim_hidden: 128
  dim_out: 10
  name: MLP

optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.0