"""Implement Any custom optimizer for baselines"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04a_optimizers.custom_optimizers.ipynb.

# %% auto #0
__all__ = ['pFedMeOptimizer', 'PerFedAvgOpt', 'APFLOptimizer', 'SCAFFOLDOptimizer', 'PerturbedGradientDescent', 'sophiag',
           'SophiaG']

# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #da03da95
import numpy as np
import os
import random
import torch
from fastcore.utils import *

# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #0fca948f
import math
from torch import Tensor
from torch.optim.optimizer import Optimizer
from typing import List, Optional

# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #5bfccba6
class pFedMeOptimizer(Optimizer):
    def __init__(self, params, lr=0.01, lambda_=0.1 , mu = 0.001):
        if lr < 0.0:
            raise ValueError("Invalid learning rate: {}".format(lr))
        defaults = dict(lr=lr, lambda_=lambda_, mu = mu)
        super(pFedMeOptimizer, self).__init__(params, defaults)
    
    def step(self, local_weight_updated, closure=None):
        for group in self.param_groups:
            for p, localweight in zip( group['params'], local_weight_updated.parameters()):
                p.data = p.data - group['lr'] * (p.grad.data + group['lambda_'] * (p.data - localweight.data) + group['mu']*p.data)
        return group['params']
    
    def update_param(self, local_weight_updated, closure=None):
        loss = None
        if closure is not None:
            loss = closure
        weight_update = local_weight_updated.copy()
        for group in self.param_groups:
            for p, localweight in zip( group['params'], weight_update):
                p.data = localweight.data
        #return  p.data
        return  group['params']

# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #d361cc6f
class PerFedAvgOpt(Optimizer):
    def __init__(self, params, lr):
        defaults = dict(lr=lr)
        super(PerFedAvgOpt, self).__init__(params, defaults)

    def step(self, beta=0):
        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None:
                    continue
                d_p = p.grad.data
                if(beta != 0):
                    p.data.add_(other=d_p, alpha=-beta)
                else:
                    p.data.add_(other=d_p, alpha=-group['lr'])


# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #f4cac912
class APFLOptimizer(Optimizer):
    def __init__(self, params, lr):
        defaults = dict(lr=lr)
        super(APFLOptimizer, self).__init__(params, defaults)

    def step(self, beta=1, n_k=1):
        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None:
                    continue
                d_p = beta * n_k * p.grad.data
                p.data.add_(-group['lr'], d_p)




# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #fc2b785b
class SCAFFOLDOptimizer(Optimizer):
    def __init__(self, params, lr):
        defaults = dict(lr=lr)
        super(SCAFFOLDOptimizer, self).__init__(params, defaults)

    def step(self, server_cs, client_cs):
        for group in self.param_groups:
            for p, sc, cc in zip(group['params'], server_cs, client_cs):
                p.data.add_(other=(p.grad.data + sc - cc), alpha=-group['lr'])


# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #48fa6f92
class PerturbedGradientDescent(Optimizer):
    def __init__(self, params, lr=0.01, mu=0.0):
        default = dict(lr=lr, mu=mu)
        super().__init__(params, default)

    @torch.no_grad()
    def step(self, global_params, device):
        for group in self.param_groups:
            for p, g in zip(group['params'], global_params):
                g = g.to(device)
                d_p = p.grad.data + group['mu'] * (p.data - g.data)
                p.data.add_(d_p, alpha=-group['lr'])


# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #69fcece1
def _single_tensor_sophiag(params: List[Tensor],
                         grads: List[Tensor],
                         exp_avgs: List[Tensor],
                         hessian: List[Tensor],
                         state_steps: List[Tensor],
                         *,
                         bs: int,
                         beta1: float,
                         beta2: float,
                         rho: float,
                         lr: float,
                         weight_decay: float,
                         maximize: bool,
                         capturable: bool):

    for i, param in enumerate(params):
        grad = grads[i] if not maximize else -grads[i]
        exp_avg = exp_avgs[i]
        hess = hessian[i]
        step_t = state_steps[i]

        if capturable:
            assert param.is_cuda and step_t.is_cuda and bs.is_cuda 
            
        if torch.is_complex(param):
            grad = torch.view_as_real(grad)
            exp_avg = torch.view_as_real(exp_avg)
            hess = torch.view_as_real(hess)
            param = torch.view_as_real(param)

        # update step
        step_t += 1

        # Perform stepweight decay
        param.mul_(1 - lr * weight_decay)

        # Decay the first and second moment running average coefficient
        exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
        
        if capturable:
            step_size = lr 
            step_size_neg = step_size.neg()

            ratio = (exp_avg.abs() / (rho * bs * hess + 1e-15)).clamp(None,1)
            param.addcmul_(exp_avg.sign(), ratio, value=step_size_neg)
        else:
            step_size_neg = - lr 
            
            ratio = (exp_avg.abs() / (rho * bs * hess + 1e-15)).clamp(None,1)
            param.addcmul_(exp_avg.sign(), ratio, value=step_size_neg)

# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #e9fec011
def sophiag(params: List[Tensor],
          grads: List[Tensor],
          exp_avgs: List[Tensor],
          hessian: List[Tensor],
          state_steps: List[Tensor],
          capturable: bool = False,
          *,
          bs: int,
          beta1: float,
          beta2: float,
          rho: float,
          lr: float,
          weight_decay: float,
          maximize: bool):

    if not all(isinstance(t, torch.Tensor) for t in state_steps):
        raise RuntimeError("API has changed, `state_steps` argument must contain a list of singleton tensors")

    
    func = _single_tensor_sophiag

    func(params,
         grads,
         exp_avgs,
         hessian,
         state_steps,
         bs=bs,
         beta1=beta1,
         beta2=beta2,
         rho=rho,
         lr=lr,
         weight_decay=weight_decay,
         maximize=maximize,
         capturable=capturable)

# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #20c1ab18
class SophiaG(Optimizer):
    def __init__(self, params, lr=1e-4, betas=(0.965, 0.99), rho = 0.04,
         weight_decay=1e-1, *, maximize: bool = False,
         capturable: bool = False):
        if not 0.0 <= lr:
            raise ValueError("Invalid learning rate: {}".format(lr))
        if not 0.0 <= betas[0] < 1.0:
            raise ValueError("Invalid beta parameter at index 0: {}".format(betas[0]))
        if not 0.0 <= betas[1] < 1.0:
            raise ValueError("Invalid beta parameter at index 1: {}".format(betas[1]))
        if not 0.0 <= rho:
            raise ValueError("Invalid rho parameter at index 1: {}".format(rho))
        if not 0.0 <= weight_decay:
            raise ValueError("Invalid weight_decay value: {}".format(weight_decay))
        defaults = dict(lr=lr, betas=betas, rho=rho, 
                        weight_decay=weight_decay, 
                        maximize=maximize, capturable=capturable)
        super(SophiaG, self).__init__(params, defaults)



# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #a12b9225
@patch
def __setstate__(self: SophiaG, state):
        super().__setstate__(state)
        for group in self.param_groups:
            group.setdefault('maximize', False)
            group.setdefault('capturable', False)
        state_values = list(self.state.values())
        step_is_tensor = (len(state_values) != 0) and torch.is_tensor(state_values[0]['step'])
        if not step_is_tensor:
            for s in state_values:
                s['step'] = torch.tensor(float(s['step']))

# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #2b575a20
@patch
@torch.no_grad()
def update_hessian(self: SophiaG):
    for group in self.param_groups:
        beta1, beta2 = group['betas']
        for p in group['params']:
            if p.grad is None:
                continue
            state = self.state[p]

            if len(state) == 0:
                state['step'] = torch.zeros((1,), dtype=torch.float, device=p.device) \
                    if self.defaults['capturable'] else torch.tensor(0.)
                state['exp_avg'] = torch.zeros_like(p, memory_format=torch.preserve_format)
                state['hessian'] = torch.zeros_like(p, memory_format=torch.preserve_format)
            
            if 'hessian' not in state.keys():
                state['hessian'] = torch.zeros_like(p, memory_format=torch.preserve_format)

            state['hessian'].mul_(beta2).addcmul_(p.grad, p.grad, value=1 - beta2)



# %% ../../nbs/04a_optimizers.custom_optimizers.ipynb #e072e5d2
@patch
@torch.no_grad()
def step(self: SophiaG, closure=None, bs=5120):
    loss = None
    if closure is not None:
        with torch.enable_grad():
            loss = closure()

    for group in self.param_groups:
        params_with_grad = []
        grads = []
        exp_avgs = []
        state_steps = []
        hessian = []
        beta1, beta2 = group['betas']

        for p in group['params']:
            if p.grad is None:
                continue
            params_with_grad.append(p)
            
            if p.grad.is_sparse:
                raise RuntimeError('Hero does not support sparse gradients')
            grads.append(p.grad)
            state = self.state[p]
            # State initialization
            if len(state) == 0:
                state['step'] = torch.zeros((1,), dtype=torch.float, device=p.device) \
                    if self.defaults['capturable'] else torch.tensor(0.)
                state['exp_avg'] = torch.zeros_like(p, memory_format=torch.preserve_format)
                state['hessian'] = torch.zeros_like(p, memory_format=torch.preserve_format)
            
            if 'hessian' not in state.keys():
                state['hessian'] = torch.zeros_like(p, memory_format=torch.preserve_format)                

            exp_avgs.append(state['exp_avg'])
            state_steps.append(state['step'])
            hessian.append(state['hessian'])
            
            if self.defaults['capturable']:
                bs = torch.ones((1,), dtype=torch.float, device=p.device) * bs

        sophiag(params_with_grad,
                grads,
                exp_avgs,
                hessian,
                state_steps,
                bs=bs,
                beta1=beta1,
                beta2=beta2,
                rho=group['rho'],
                lr=group['lr'],
                weight_decay=group['weight_decay'],
                maximize=group['maximize'],
                capturable=group['capturable'])

    return loss

