"""data loading and preparation utilities start here to understand the data journey."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01e_data.ipynb.

# %% auto #0
__all__ = ['get_preprocessor', 'init_data', 'get_block', 'prepare_dl_dist', 'prepare_dl']

# %% ../../nbs/01e_data.ipynb #899d769f
import importlib
from dataclasses import dataclass
from typing import Dict
from omegaconf import OmegaConf, DictConfig
from dataclasses import is_dataclass, asdict

import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.distributed as dist

from fastcore.utils import *
from flwr_datasets import FederatedDataset
from flwr_datasets.partitioner import *
from flwr_datasets.preprocessor import Merger

from .vision import VisionBlock
from ..core import get_clean_kwargs

# %% ../../nbs/01e_data.ipynb #c65ffc49
def get_preprocessor(cfg):
    dataset_dict = {"train": "train", "test": "test"}
    if cfg.data.name == "tinyimagenet":
        dataset_dict = {"train": "train", "valid": "valid"}
        
    merger = Merger(
        merge_config={
             "train": tuple(list(key for key in dataset_dict.keys())),
            }
        )
    return merger

# %% ../../nbs/01e_data.ipynb #55505584
def init_data(cfg):
    if cfg.partitioner.cls in ["GroupedDistributionPartitioner", "GroupedClassPartitioner", "VariableClassPartitioner", "RotatedPatchedPartitioner"]:
        module = importlib.import_module("fedai.data.vision.partitioners")
        
    else: 
        module = importlib.import_module("flwr_datasets.partitioner")
    
    partitioner_cls = getattr(module, cfg.partitioner.cls)
    kwargs = get_clean_kwargs(cfg.partitioner)
    kwargs.pop("cls", None)
    
    partitioner = partitioner_cls(**kwargs, seed= cfg.random_seed)    
    preprocessor = get_preprocessor(cfg)
    
    fds = FederatedDataset(dataset= cfg.data.hf_name, 
                           partitioners= {"train": partitioner},
                           preprocessor= preprocessor,
                           seed= 42)
    
    return fds

# %% ../../nbs/01e_data.ipynb #189feeed
def get_block(cfg, client_id, fds= None, train=True):

    if cfg.data.modality.lower() == "vision":
        return VisionBlock(cfg.data, client_id, train= train, fds= fds, seed= 42)

# %% ../../nbs/01e_data.ipynb #c30b3e12
def prepare_dl_dist(
        cfg,
        client_id,
        fds,
        train= True,
        collator=torch.utils.data.default_collate,
):
    block = get_block(cfg= cfg, client_id= client_id, fds= fds, train= train)

    dist_sampler = torch.utils.data.distributed.DistributedSampler(block)

    data_loader = torch.utils.data.DataLoader(
        block,
        collate_fn=collator,
        sampler=dist_sampler,
        batch_size=cfg.data.get("batch_size", 32),
        drop_last=cfg.data.get("drop_last", False),
        pin_memory=cfg.data.get("pin_memory", False),
        num_workers=cfg.data.get("num_workers", 0),
        persistent_workers=(cfg.data.get("num_workers", 0) > 0) and cfg.data.get("persistent_workers", False),
    )


    return data_loader, dist_sampler

# %% ../../nbs/01e_data.ipynb #1307d51f
def prepare_dl(cfg, client_id, fds, train=True, distributed=False):
    if distributed and torch.distributed.is_initialized():
        return prepare_dl_dist(cfg, client_id, fds, train)
    
    block = get_block(cfg, client_id, fds, train)
    dl = torch.utils.data.DataLoader(block, batch_size= cfg.data.batch_size, shuffle= True if train else False) # TODO: make sure you put batch_size to dataConfig keys
    return dl
