project_name: main_cifar10_20clients

algorithm: perfedavg
num_clients: 20
n_rounds: 200 
m: 1.0
local_epochs: 5 
agg: one_model


beta: 0.005


client_selector: BaseClientSelector
writer: WandbWriter


root_dir: /scratch/project_2009050/
save_dir : models
res_dir: results
log_dir: logs
state_dir: local_output_

training_metrics: [accuracy_score]
test_metrics: [accuracy_score]

data:
  data_dir: /scratch/project_2009050/
  modality: [Vision]
  batch_size: 32
  name: cifar10
  partitioner: 
    name: PathologicalPartitioner
    kwargs:
      num_classes_per_partition: 2
      class_assignment_mode: first-deterministic
  num_classes: 10
  classes: [plane, car, bird, cat, deer, dog, frog, horse, ship, truck]


model:
  name: lenet_cifar10
  img_size: [3, 32, 32]
  hidden_dim: 512
  num_classes: 10


optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 0.0